const path = require('node:path');

const root = __dirname;

module.exports = {
  apps: [
    {
      name: 'forum-api',
      cwd: path.join(root, 'apps/api'),
      script: 'dist/main.js',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      kill_timeout: 10_000,
      max_memory_restart: '768M',
      time: true,
      error_file: path.join(root, 'logs/api-error.log'),
      out_file: path.join(root, 'logs/api-out.log'),
      env_production: { NODE_ENV: 'production' },
    },
    {
      name: 'forum-web',
      cwd: path.join(root, 'apps/web'),
      script: path.join(root, 'apps/web/node_modules/next/dist/bin/next'),
      args: 'start -p 3001',
      interpreter: 'node',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      kill_timeout: 10_000,
      max_memory_restart: '768M',
      time: true,
      error_file: path.join(root, 'logs/web-error.log'),
      out_file: path.join(root, 'logs/web-out.log'),
      env_production: { NODE_ENV: 'production' },
    },
    {
      name: 'forum-admin',
      cwd: path.join(root, 'apps/admin'),
      script: path.join(root, 'apps/admin/node_modules/next/dist/bin/next'),
      args: 'start -p 3002',
      interpreter: 'node',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      kill_timeout: 10_000,
      max_memory_restart: '768M',
      time: true,
      error_file: path.join(root, 'logs/admin-error.log'),
      out_file: path.join(root, 'logs/admin-out.log'),
      env_production: { NODE_ENV: 'production' },
    },
    {
      name: 'forum-merchant',
      cwd: path.join(root, 'apps/merchant'),
      script: path.join(root, 'apps/merchant/node_modules/next/dist/bin/next'),
      args: 'start -p 3003',
      interpreter: 'node',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      kill_timeout: 10_000,
      max_memory_restart: '768M',
      time: true,
      error_file: path.join(root, 'logs/merchant-error.log'),
      out_file: path.join(root, 'logs/merchant-out.log'),
      env_production: { NODE_ENV: 'production' },
    },
  ],
};
